---
# Run StewardBot on kubernetes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sulwatcher
  namespace: tool-stewardbots
  labels:
    name: sulwatcher
    # Mount NFS
    toolforge: tool
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sulwatcher
      toolforge: tool
  template:
    metadata:
      labels:
        name: sulwatcher
        toolforge: tool
    spec:
      containers:
        - name: bot
          image: docker-registry.tools.wmflabs.org/toolforge-python37-sssd-base:latest
          command: [ "/data/project/stewardbots/stewardbots/SULWatcher/manage.sh", "run" ]
          workingDir: /data/project/stewardbots
          env:
            - name: HOME
              value: /data/project/stewardbots
          imagePullPolicy: Always
